### ISSUE TITLE
about.md says we use Fuse, but we don't (yet)

### ISSUE THREAD

**Issue by cmosher-redhat** [Emergency-Response-Demo/erdemo.io#2]
Under "What does the stack include" in the About This Demo section, Red Hat Fuse is listed as one of the technologies.  However that is not currently in use in the demo.  We are still looking at potential use cases / vectors to apply it.  In the meantime, please remove it from the list.

**Comment by sshaaf** [comment]
Agreed, this has been on the backlog far to long. will remove it

**Comment by sshaaf** [comment]
removed fuse
