### ISSUE TITLE
 Update the application architecture diagram - Remove reference to Fuse

### ISSUE THREAD

**Issue by darbyredhat** [Emergency-Response-Demo/erdemo.io#9]
On the erdemo.io website, [the application architecture diagram](https://www.erdemo.io/architecture/) shows Fuse as one of the technologies used. However, Fuse is not used in the project (yet). Update the diagram to remove the reference to Fuse.

This was originally reported by Rodrigo Ramalho on 3 March 2020 via chat message.

**Comment by sshaaf** [comment]
Thanks the PR is now merged.
